name: Lint RELEASE Variant

on:
  workflow_call:

jobs:
  lint:
    name: Linting RELEASE variant
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Load Google Services
        env:
          DATA: ${{ secrets.GOOGLE_SERVICES_JSON }}
        run: touch ./app/google-services.json && echo $GOOGLE_SERVICES_JSON | base64 -di > ./app/google-services.json

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Execute Gradle command - lintRelease
        run: ./gradlew lintRelease
