name: Unit Tests on RELEASE

on:
  workflow_call:

jobs:
  run_tests:
    name: Testing release variant
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Load Google Services
        env:
          DATA: ${{ secrets.GOOGLE_SERVICES_JSON }}
        run: |
          # Print the base64 data to inspect its format
          echo "$DATA" | head -c 100

          # Try decoding the base64 string to google-services.json
          if ! echo "$DATA" | base64 -di > app/google-services.json; then
            echo "Base64 decoding failed! Check your encoded secret." >&2
            exit 1
          fi
    
          # Check if the file is a valid JSON file
          if ! jq . app/google-services.json > /dev/null 2>&1; then
            echo "google-services.json is NOT valid JSON!" >&2
            exit 1
          fi

          # Output the first few lines for debugging purposes (optional)
          head -n 10 app/google-services.json
          
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Execute Gradle command - testReleaseUnitTest
        run: ./gradlew testReleaseUnitTest
