name: On Pull Request Opened

on:
  pull_request:
    branches: [ develop ]

jobs:
  run_tests:
    name: Testing debug variant
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Load Google Services
        env:
          DATA: ${{ secrets.GOOGLE_SERVICES_JSON_DEBUG }}
        run: |
          echo "$DATA" | base64 -d > app/google-services.json
    
          if ! jq . app/google-services.json > /dev/null 2>&1; then
            echo "google-services.json is NOT a valid JSON!" >&2
            cat app/google-services.json
            exit 1
          fi

          head -n 10 app/google-services.json

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Execute Gradle command - testDebugUnitTest
        run: ./gradlew testDebugUnitTest

      - name: Execute Gradle command - lintDebug
        run: ./gradlew lintDebug
